config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  scope "(:locale)", locale: /es|en/ do

    get 'member/:id/edit_membership' => 'members#edit_membership', as: :member_edit_membership

    resources :members do
      member do
        put :add_role
      end
    end

    resources :news
    resources :posts
    resources :subjects do
      resources :loads, only: [:index, :new, :create]
      resources :materials, only: [:index, :new, :create, :destroy]
    end
    resources :loads, only: [:update]

    resources :periods do
      resources :subjects, only: [:index, :new, :create]
    end

    resources :subjects, only: [:show, :edit, :update, :destroy]
    get '/subjects/:id/participants', to: 'subjects#participants', as: 'subject_users'

    get '/periods_list', to: 'periods#list', as: 'periods_list'
    get '/teachers', to: 'members#teachers', as: 'members_teachers'
    get '/apiusers', to: 'members#apiusers', as: 'api_users'
    get '/members/:user_id/qualifications', to: 'members#qualifications', as: 'member_qualifications'

    devise_for :users

  end

  root 'welcome#index'
  get '/:locale' => 'welcome#index'
  

    

end

app/models/load.rb
class Load < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  belongs_to :role
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
    before_action :find_subject,  only: [:new, :create]
    load_and_authorize_resource

    def new
        
    end

    def create
        @subject = Subject.find(params[:subject_id])

        if @subject.period.end < Date.today
            flash[:alert] = "The user does not added. The period is over!"
            redirect_to subject_users_path(@subject) and return
        end

        @user = User.where(email: params[:user_email]).first

        if !@user.role_id?(params[:load][:role_id])
            flash[:alert] = "The user does not have this role!"
            redirect_to subject_users_path(@subject) and return
        end

        #@role = Role.find_by_name('profesor')
        #if @subject.users.where(:loads => {:user_id => current_user.id, :role_id => @role.id }).count <= 0
        #    flash[:alert] = "The user does not have the role teacher!"
        #    redirect_to subject_users_path(@subject) and return
        #end

        @loadFind = Load.where(user_id: @user.id, subject_id: @subject.id)

        if @loadFind.count <= 0
            
            @load = Load.new(load_params)
            @load.subject = @subject
            @load.user = @user

            if @load.save and @load.save
                flash[:notice] = "Successfully add user!" 
                redirect_to subject_users_path(@subject) and return
            else
                flash[:alert] = "Error add user!"
                redirect_to subject_users_path(@subject) and return
            end
        else
            flash[:alert] = "This user is already added!"
            redirect_to subject_users_path(@subject) and return
        end

    end

    def update
        @load = Load.find(params[:id])
        if @load.subject.period.end < Date.today
            flash[:alert] = "Error. The period is over!"
            redirect_to subject_users_path(@load.subject) and return
        end

        if @load.update_attributes(load_params)
            flash[:notice] = "Successfully edit!" 
            redirect_to subject_users_path(@load.subject) and return
        else
            flash[:alert] = "Error!"
            subject_users_path(@load.subject) and return
        end 
    end

    private

    def find_subject
        @subject = Subject.find(params[:subject_id])
    end

    def load_params
        params.require(:load).permit(:subject, :role_id, :qualification)
    end

end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/views/loads/new.html.erb
<% content_for :breadcrumb do %>
<%= link_to "Periods", periods_list_path, class: 'breadcrumb' %>
<%= link_to "Subjects - " + @subject.period.year.to_s + ' - ' + @subject.period.semester, period_subjects_path(@subject.period.id), class: 'breadcrumb' %>
<%= link_to @subject.name, subject_path(@subject), class: 'breadcrumb' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 m6 grey darken-4 subsection with-image-users">
        <img src="" alt="">
        <div class="header-section-img white-text">
            <h4><%= @subject.name.capitalize %> - <%= @subject.code %></h4>
            <b><%= @subject.period.year %> - <%= @subject.period.semester %></b>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-3">
        <i class="fa fa-book large"></i>
        <h5 class="white-text">Material</h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to "View", subject_path(@subject), :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-3">
        <i class="fa fa-users large "></i>
        <h5 class="white-text">Participants</h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to "View", subject_users_path(@subject), :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
</div>
<div class="row no-margin-bottom">
    <div class="col s12 m2 grey darken-4">
        <p>
            <%= link_to "Add", new_subject_load_path(@subject), :class => 'waves-effect waves-light btn btn-block' %>
        </p>
    </div>
    <div class="col s12 m10 white" style="padding:25px;">

        
        
        
    </div>
</div>