config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  scope "(:locale)", locale: /es|en/ do

    get 'member/:id/edit_membership' => 'members#edit_membership', as: :member_edit_membership

    resources :members do
      member do
        put :add_role
      end
    end

    resources :news
    resources :posts
    resources :subjects do
      resources :loads, only: [:index, :new, :create]
      resources :materials, only: [:index, :new, :create, :destroy]
    end
    resources :loads, only: [:update]

    resources :periods do
      resources :subjects, only: [:index, :new, :create]
    end

    resources :subjects, only: [:show, :edit, :update, :destroy]
    get '/subjects/:id/participants', to: 'subjects#participants', as: 'subject_users'

    get '/periods_list', to: 'periods#list', as: 'periods_list'
    get '/teachers', to: 'members#teachers', as: 'members_teachers'
    get '/apiusers', to: 'members#apiusers', as: 'api_users'
    get '/members/:user_id/qualifications', to: 'members#qualifications', as: 'member_qualifications'

    devise_for :users

  end

  root 'welcome#index'
  get '/:locale' => 'welcome#index'
  

    

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :period
  has_many :loads
  has_many :materials
  has_many :users, :through => :loads

  def haveUser?(user)
    !users.find_by_id(user).nil?
      
  end

  def qualification(user)
      loads.where('loads.user_id == '+ user.to_s ).first.qualification
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
    before_action :find_subject,  only: [:show, :update, :destroy, 'participants']
    load_and_authorize_resource
    
    def index
        if current_user.role?('super_admin')
            @subjects = Subject.order('created_at DESC').where(period_id: params[:period_id]).page params[:page]
        else
            @subjects = current_user.subjects.order('created_at DESC').where(period_id: params[:period_id]).page params[:page]
        end
        @period = Period.find(params[:period_id])
    end

    def new
        @subject = Subject.new
        @period = Period.find(params[:period_id])
    end

    def show
        @enabled = true
        if @subject.period.end < Date.today
            @enabled = false
        end
        @material = Material.new

        @loadCharge = @subject.loads.where(:user_id => current_user.id)

        if @loadCharge.any?
            @qualification = @loadCharge.first.qualification
        end
    end

    def participants
        @enabled = true
        if @subject.period.end < Date.today
            @enabled = false
        end
        @loads = Load.where(subject_id: params[:id]).page params[:page]
        @load = Load.new
    end
    
    def create
        @subject = Subject.new(subject_params)
        @period = Period.find(params[:period_id])
    
        if @user = User.where(email: params[:teacher]).first
            @load = Load.new
            @load.subject = @subject
            @load.user = @user
            @load.role = Role.where(name: 'profesor').first
            if !@load.save
                flash[:alert] = "Error creating new subject!"
                render :new and return           
            end
        end

        @subject.period = @period

        if @subject.save
            flash[:notice] = "Successfully created subject!"
            redirect_to period_subjects_path(@period)
        else
            flash[:alert] = "Error creating new subject!"
            render :new
        end
    end

    private

    def find_subject
        @subject = Subject.find(params[:id])
        @period = Period.find(@subject.period_id)
    end

    def subject_params
        params.require(:subject).permit(:name, :code)
    end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.erb
<% content_for :breadcrumb do %>
<% if can? :manage, @period %>
<%= link_to t('layout.periods.title'), periods_list_path, class: 'breadcrumb' %>
<% end %>
<%= link_to t('layout.subjects.title')+ " - " + @period.year.to_s + ' - ' + @period.semester, period_subjects_path(params[:period_id]), class: 'breadcrumb' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 m2 grey darken-4" style="min-height:100px;">
        <p> 
            <% if can? :new, Subject %>
            <%= link_to t('layout.subjects.new'), new_period_subject_path(params[:period_id]), :class => 'waves-effect waves-light btn btn-block' %>
            <% end %>
            <div class="input-field white-text white-input col s12">
                <input id="icon_prefix" type="text" class="validate">
                <label for="icon_prefix"><%= t('layout.search') %></label>
                <% if user_signed_in? %>
                <%= link_to "Qualifications", member_qualifications_path(current_user.id), :class=>"btn btn-block z-depth-0" %><br>
                <% end %>
            </div>
        </p>
        
    </div>
    <div class="col s12 m10 white" style="padding:25px;">
        <table class="responsive-table centered striped">
            <thead>
                <tr>
                    <th><%= t('layout.subjects.subject') %></th>
                </tr>
                <tbody>
                    <% @subjects.each do |subject| %>
                    <tr>
                        <td><a href="<%= subject_path(subject) %>"><%= subject.name %> - <%= subject.code %> </a></td>
                    </tr>
                    <% end %>
                </tbody>
            </thead>
            
        </table>
        <div class="right">
            <%= paginate @subjects, :params => {:controller => 'subjects', :action => 'index'} %> 
        </div>
        
    </div>
</div>

app/views/subjects/new.html.erb
<% content_for :breadcrumb do %>
<%= link_to "Periods", periods_list_path, class: 'breadcrumb' %>
<%= link_to "Subjects - " + @period.year.to_s + ' - ' + @period.semester, period_subjects_path(params[:period_id]), class: 'breadcrumb' %>
<%= link_to "New subject", new_period_subject_path, class: 'breadcrumb' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 white" style="padding:25px;">
        <%= form_for [:period, @subject] do |n| %>
        <div class="row">
            <div class="input-field col s6">
                <%= n.text_field :name, :required => true %>
                <%= n.label :name, 'Name' %>
            </div>
            <div class="input-field col s6">
                <%= n.text_field :code, :required => true %>
                <%= n.label :code, 'Code' %>
            </div>
            <div class="row" style="padding: 0 0.75rem;">
                <div class="input-field col s12 m10" >
                    <%= text_field_tag :teacher, params[:teacher], class: 'autocomplete' %>
                    <%= label_tag :teacher, 'Teacher E-mail' %>
                </div>
            </div>

        </div>
        <%= n.submit :class => 'btn red waves-effect' %>
        <% end %>
    </div>
</div>

<% content_for :scripts do %>
<script>

 $(document).ready(function() {
    $.ajax({
        url: '/teachers',
        type: 'GET',
        success: function(teachers) {
            console.log(teachers);
            $('input.autocomplete').autocomplete({
                data: teachers
            });
        },
        error: function(data) {console.log('error: '+data);}
    });


});

</script>
<% end %>

app/views/subjects/participants.html.erb
<% content_for :breadcrumb do %>
<% if can? :manage, @period %>
<%= link_to t('layout.periods.title'), periods_list_path, class: 'breadcrumb' %>
<% end %>
<%= link_to t('layout.subjects.title')+ " - " + @period.year.to_s + ' - ' + @period.semester, period_subjects_path(@period.id), class: 'breadcrumb' %>
<%= link_to @subject.name, subject_path(@subject), class: 'breadcrumb' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 m6 grey darken-4 subsection with-image-users">
        <img src="" alt="">
        <div class="header-section-img white-text">
            <h4><%= @subject.name.capitalize %> - <%= @subject.code %></h4>
            <b><%= @subject.period.year %> - <%= @subject.period.semester %></b>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-3">
        <i class="fa fa-book large"></i>
        <h5 class="white-text">Material</h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.subjects.view'), { :controller => "subjects", :action => 'show'}, :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-4 triangle">
        <i class="fa fa-users large "></i>
        <h5 class="white-text"><%= t('layout.subjects.participants') %></h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.subjects.view'), subject_users_path(@subject), :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
</div>
<div class="row no-margin-bottom">
    <% if can? :create, @load %>
    <div class="col s12 m2 grey darken-4">
        <p>
            <a class="waves-effect waves-light btn btn-block <%= 'disabled' if !@enabled %>" href="#addLoad"><%= t('layout.subjects.add') %></a>
        </p>
        <!-- Modal Structure -->
        <div id="addLoad" class="modal modal-fixed-footer">
            <%= form_for [@subject, @load] do |n| %>
            <div class="modal-content">
                <h4><%= t('layout.subjects.add_user') %></h4>
                
                <div class="row">
                    <div class="row" style="padding: 0 0.75rem;">
                        <div class="input-field col s12 m8" >
                            <%= text_field_tag :user_email, nil,  class: 'autocomplete' %>
                            <%= label_tag :user, t('layout.subjects.email') %>
                        </div>
                        <div class="input-field col s4">
                            <%= n.select :role_id, Role.where(name: ['profesor', 'estudiante']).collect {|p| [ p.name, p.id ] }.prepend(['Select a role', '']), {:disabled => ''}%>
                            <%= n.label :role_id, t('layout.subjects.role') %>
                        </div>
                    </div>
                </div>
                
                
            </div>
            <div class="modal-footer">
                <%= n.submit t('layout.subjects.add'), :class => 'modal-action waves-effect waves-green btn-flat' %>
            </div>
            <% end %>
        </div>
    </div>
    <% end %>
    <div class="col s12 m10 white" style="padding:25px;">

        <table>
            <thead>
                <tr>
                    <th><%= t('layout.subjects.email') %></th>
                    <th><%= t('layout.subjects.role') %></th>
                    <th><%= t('layout.subjects.qualification') %></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @loads.each do |l| %>
                
                <tr>

                    <td><%= l.user.email %></td>
                    <td><%= l.role.name %></td>
                    <td><%= l.qualification %></td>
                    <% if l.role.name == 'estudiante' %>
                    <% if can? :update, Load %>
                    <td>

                        <%= form_for(l) do |l| %>
                        <div class="input-field inline col s6">
                            <%= l.text_field :qualification %>
                        </div>
                        <% end %>

                    </td>
                    <% end %>
                    <% end %>
                </div>
            </tr>
            <% end %>
        </tbody>
    </table>
    <div class="right">
        <%= paginate @loads, :params => {:controller => 'subjects', :action => 'participants'} %> 
    </div>

</div>
</div>

<% content_for :scripts do %>
<script>

    $(document).ready(function(){

        $('.modal').modal();
        $.ajax({
            url: '/apiusers',
            type: 'GET',
            success: function(users) {
                console.log(users);
                $('input.autocomplete').autocomplete({
                    data: users
                });
            },
            error: function(data) {console.log('error: '+data);}
        });
    });



</script>
<% end %>

app/views/subjects/show.html.erb
<% content_for :breadcrumb do %>
<% if can? :manage, @period %>
<%= link_to t('layout.periods.title'), periods_list_path, class: 'breadcrumb' %>
<% end %>
<%= link_to t('layout.subjects.title')+ " - " + @period.year.to_s + ' - ' + @period.semester, period_subjects_path(@period.id), class: 'breadcrumb' %>
<%= link_to @subject.name, subject_path(@subject), class: 'breadcrumb' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 m6 grey darken-4 subsection with-image-users">
        <img src="" alt="">
        <div class="header-section-img white-text">
            <h4><%= @subject.name.capitalize %> - <%= @subject.code %></h4>
            <b><%= @subject.period.year %> - <%= @subject.period.semester %></b>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-4 triangle">
        <i class="fa fa-book large"></i>
        <h5 class="white-text">Material</h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.subjects.view'), { :controller => "subjects", :action => 'show'}, :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
    <div class="col s12 m3 subsection grey darken-3">
        <i class="fa fa-users large "></i>
        <h5 class="white-text"><%= t('layout.subjects.participants') %></h5>
        <span class="white-text header-number"><b></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.subjects.view'), subject_users_path(@subject), :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
</div>
<div class="row no-margin-bottom">
    
    <div class="col s12 m2 grey darken-4">
        <h6 class="grey-text"><%= t('layout.subjects.qualification') %>:</h6>
        <h5 class="grey-text"><%= @qualification %></h5>
        <% if can? :create, @material %>
        <p>
            <a class="waves-effect waves-light btn btn-block <%= 'disabled' if !@enabled %>" href="#addMaterial"><%= t('layout.subjects.upload') %></a>
        </p>
        <!-- Modal Structure -->
        <div id="addMaterial" class="modal">
            <%= form_for [@subject, @material], html: { multipart: true } do |m| %>
            <div class="modal-content">
                <h4><%= t('layout.subjects.add_material') %></h4>
                
                <div class="row">
                    <div class="row" style="padding: 0 0.75rem;">
                        <div class="input-field col s12" >
                            <%= m.text_field :name %>
                            <%= m.label :name, t('layout.subjects.name') %>
                        </div>
                        <div class="file-field input-field col s12">
                            <div class="btn">
                                <span><%= t('layout.subjects.file') %></span>
                                <%= m.file_field :attachment  %>
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>
                    </div>
                </div>
                
                
            </div>
            <div class="modal-footer">
                <%= m.submit t('layout.subjects.upload'), :class => 'modal-action waves-effect waves-green btn-flat' %>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
    
    <div class="col s12 m10 white" style="padding:25px;">

        <table>
            <thead>
                <tr>
                    <th><%= t('layout.subjects.date') %></th>
                    <th><%= t('layout.subjects.name') %></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <% @subject.materials.order('created_at DESC').each do |material| %>
                <tr>
                    <td><%= material.created_at.strftime('%d / %m / %Y') %></td>
                    <td><%= material.name %></td>
                    <td><%= link_to t('layout.subjects.download'), material.attachment_url %></td>
                    <% if can? :destroy, @material and @enabled %>
                    <td><%= button_to t('layout.subjects.delete'),  subject_material_path(@subject, material.id), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{material.name}?" %></td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>
        
    </div>
</div>

<% content_for :scripts do %>
<script>

    $(document).ready(function(){
        $('.modal').modal();
    });

</script>
<% end %>