config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  scope "(:locale)", locale: /es|en/ do

    get 'member/:id/edit_membership' => 'members#edit_membership', as: :member_edit_membership

    resources :members do
      member do
        put :add_role
      end
    end

    resources :news
    resources :posts
    resources :subjects do
      resources :loads, only: [:index, :new, :create]
      resources :materials, only: [:index, :new, :create, :destroy]
    end
    resources :loads, only: [:update]

    resources :periods do
      resources :subjects, only: [:index, :new, :create]
    end

    resources :subjects, only: [:show, :edit, :update, :destroy]
    get '/subjects/:id/participants', to: 'subjects#participants', as: 'subject_users'

    get '/periods_list', to: 'periods#list', as: 'periods_list'
    get '/teachers', to: 'members#teachers', as: 'members_teachers'
    get '/apiusers', to: 'members#apiusers', as: 'api_users'
    get '/members/:user_id/qualifications', to: 'members#qualifications', as: 'member_qualifications'

    devise_for :users

  end

  root 'welcome#index'
  get '/:locale' => 'welcome#index'
  

    

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new                          # guest user 

    if user.role?('super_admin')
      can :read, :all
      can :manage, News
      can :manage, Post
      can :manage, Period
      can :manage, Subject
      can :manage, Load
      can :manage, Material
      can :qualifications, User
    else
      can :read, News
      if User.exists?(user)
        can :qualifications, User
        can :read, Post
        can [:read, :participants], Subject do |s|
          s.users.where(:loads => {:user_id => user.id}).any?
        end
        if user.role?('profesor')
          can [:create, :destroy], Material
          can [:create], Load
          can :update, Load
        end
      end 
    end

  end
end

app/models/load.rb
class Load < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  belongs_to :role
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :subject
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/news.rb
class News < ActiveRecord::Base
    paginates_per 4
    belongs_to :user
    mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model.
end

app/models/period.rb
class Period < ActiveRecord::Base
    has_many :subjects
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
    has_and_belongs_to_many :users
    accepts_nested_attributes_for :users 
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :period
  has_many :loads
  has_many :materials
  has_many :users, :through => :loads

  def haveUser?(user)
    !users.find_by_id(user).nil?
      
  end

  def qualification(user)
      loads.where('loads.user_id == '+ user.to_s ).first.qualification
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10
  has_many :news
  has_and_belongs_to_many :roles 
  accepts_nested_attributes_for :roles
  has_many :loads
  has_many :subjects, through: :loads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def role?( role ) 
        !roles.find_by_name( role ).nil?
    end 

    def role_id?( role ) 
        !roles.find_by_id( role ).nil?
    end 

    def active_for_authentication? 
        super && approved? 
    end

    def subjectLoad?(subject)
        !loads.find_by_subject_id(subject).nil?
    end

    def inactive_message 
        if !approved? 
          :not_approved 
        else 
            super # Use whatever other message 
        end 
    end
    
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    before_action :find_news, only: [:edit, :update, :show, :delete]
    load_and_authorize_resource

    def index
        if params[:highlighted] == "true"
            @news = News.where(highlighted: true).order(:created_at).page params[:page]
            @all_news = false;
        else
            @news = News.order('created_at DESC').page params[:page]
            @all_news = true;
        end
        @countAll = News.count
    end

    def new
        @news = News.new
    end

    def create
        @news = News.new(news_params)
        @news.user = current_user
        if @news.save
            flash[:notice] = "Successfully created piece of news!"
            redirect_to news_index_path
        else
            flash[:alert] = "Error creating new piece of news!"
            render :new
        end
    end

    def edit
    end

    def update
        if @news.update_attributes(news_params)
            flash[:notice] = "Successfully updated piece of news!"
            redirect_to news_index_path
        else
            flash[:alert] = "Error updating piece of news!"
            render :edit
        end
    end

    def show
    end

    def destroy
        if @news.destroy
            flash[:notice] = "Successfully deleted piece of news!"
            redirect_to news_index_path
        else
            flash[:alert] = "Error updating new!"
        end
    end

    private

    def news_params
        params.require(:news).permit(:title, :body, :highlighted, :color, :feactured, :image)
    end

    def find_news
        @new = News.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="red lighten-5 z-depth-1" id="error_explanation">
      <h5><i class="fa fa-exclamation medium" aria-hidden="true"></i>
      <b>#{sentence}</b></h6>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universidad XYZ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/partials/navbars' %>
    <!-- Miga de pan -->
    <div class="row padding-top-20">
      <div class="col m12">
        <nav class="transparent z-depth-0">
          <div class="nav-wrapper">
            <div class="col s12 orange-text text-acent-3">
              <%= link_to t('layout.navbar.home'), root_path, class: 'breadcrumb' %>
              <%= yield :breadcrumb %>
            </div>
          </div>
        </nav>
      </div>
    </div>

  </div>
  <!-- Contenido de la pagina -->
  <div class="container">
    <%= yield %>
  </div>

  <!-- Footer -->
  <div class="container">
    <%= render 'layouts/partials/footer' %>
  </div>

  
  <!-- Scripts -->
  <script>
    // iniciar tootips
    $(document).ready(function(){
      $('.tooltipped').tooltip({delay: 50});
    });
    //iniciar dorpdown

    $(".dropdown-button").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: true, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
        
    // iniciar la barra lateral
    $(".button-collapse").sideNav();

    $(function() {
      // solventar errores de materialize y rails

      $('select').material_select();

      //inicializador de los toast
      <% if notice %>
      Materialize.toast('<%= notice %>', 4000, 'green')
      <% end %>
      <% if alert %>
      Materialize.toast('<%= alert %>', 4000, 'red')
      <% end %>

      //para los elementos seleccionados en la navbar sean active en funcion de su href
      var url = window.location.toString();
      console.log(url);
      if (url.match('#')) {
        url = url.split('#')[0];
        console.log(url);
      }
      var element = $('.tabs .tab a').filter(function() {
        return this.href == url;
      }).addClass('active');

      console.log(element.parent());

      if(!element.parent().is('li.tab')){
        $('.indicator').removeClass('indicator');
        $('.tabs .tab a').removeClass('active');
      }
    });

  </script>

  <%= yield :scripts %>

</body>
</html>

app/views/layouts/partials/_footer.html.erb
<div class="row no-margin-bottom">
  <div class="col s12">
    <footer class="page-footer">

      <div class="row" style="margin-bottom:0;">
        <div class="col s12 m12 l5 grey darken-4" style="min-height:210px;">
          <div class="container-fluid">
            <h5 class="grey-text">Universidad del Valle</h5>
            <p class="grey-text text-darken-1">Unversity description</p>
            <a target="_blank" data-position="top" data-delay="50" data-tooltip="<%= t('layout.navbar.repo') %>" href="https://bitbucket.org/stipelson/campusvirtual" class="tooltipped"><i class="fa fa-bitbucket" aria-hidden="true"></i></a>
          </div>
        </div>
        <div class="col s12 m12 l7 grey darken-3" style="min-height:160px;">
          <div class="container-fluid">
            <h5 class="grey-text">Links</h5>
            <ul>
            <li><a class="grey-text text-darken-1" href="#!"><%= t('layout.navbar.home') %></a></li>
              <li><a class="grey-text text-darken-1" href="#!">Blog</a></li>
            </ul>
          </div>
        </div>
        <div class="col s12 m12 l7" style="padding:0;">
          <div class="footer-copyright grey lighten-4">
            <div class="container-fluid-copyright">
              © 2016 Copyright Text
              <%= link_to "ES", { locale: "es"}, {class: 'right'} %>
              <%= link_to "EN", { locale: "en"}, {class: 'right'} %>
            </div>
          </div>
        </div>
      </div>

    </footer>
  </div>
</div>

app/views/layouts/partials/_navbars.html.erb
<div class="row no-margin-bottom">
  <div class="col s12 m12 l6" style="padding:0;">
    <!-- Headore principal con el logo -->
    <nav class="nav-extended white" >
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo black-text hide-on-med-and-down" style="margin:10px;"><%= image_tag("logo.png", height: '70') %></a>
        <a href="<%= root_path %>" class="brand-logo black-text hide-on-large-only" style="margin:5px;"><%= image_tag("logo_small.png", height: '55') %></a>
        <ul id="nav-mobile1" class="right hide-on-med-and-down">
          <li>
            <li><a href="<%= root_path %>" class="btn waves-effect waves-red waves-accent-4 red-text text-accent-4 white z-depth-0 bordered "><%= t('layout.navbar.curses') %></a></li>
          </li>
        </ul>
        <ul class="tabs tabs-transparent hide-on-med-and-down">
          <li class="tab right"><a target="_blank" data-position="bottom" data-delay="50" data-tooltip="<%= t('layout.navbar.repo') %>" href="https://bitbucket.org/stipelson/campusvirtual" class="tooltipped"><i class="fa fa-bitbucket" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>
  <div class="col s12 m12 l6" style="padding:0;">
    <!-- Barra de navegacion gris con el menu principal -->
    <nav class="nav-extended grey darken-4">
      <div class="nav-wrapper">
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to t('layout.navbar.home'), root_path %></li>
          <li class="<%= 'active' if current_page?(news_index_path) %>"><%= link_to t('layout.navbar.news'), news_index_path %></li>
          <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to 'Blog', posts_path %></li>
          <!-- Menu desplegable de cursos -->
          <% if user_signed_in?%>
          <% if current_user.role?('super_admin') %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= t('layout.navbar.manage') %><i class="material-icons right">arrow_drop_down</i></a></li>
          <% end %>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to t('layout.navbar.home'), root_path %></li>
          <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to 'Blog', posts_path %></li>
        </ul>
        <!-- Dropdown Admin Structure -->
        <ul id="dropdown1" class="dropdown-content">
          <% if can? :read, @users %>
          <li class="<%= 'active' if current_page?(members_path) %>"><%= link_to t('layout.navbar.users'), members_path %></li>
          <% end %>
          <% if can? :read, @periods %>
          <li class="<%= 'active' if current_page?(periods_path) %>"><%= link_to 'Periodos', periods_path %></li>
          <% end %>
          <li class="divider"></li>
          <% if can? :create, Subject %>
          <li class="<%= 'active' if current_page?(periods_list_path) %>"><%= link_to 'Cursos', periods_list_path %></li>
          <% end %>
        </ul>

        <ul class="tabs tabs-transparent grey darken-3">
          <%= render 'devise/menu/login_items' %>
          <%= render 'devise/menu/registration_items' %>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/partials/_slider.html.erb
<div class="slider">
    <ul class="slides">
        <% @sliderNews.each do |pnews| %>
        <li>
            <img src="<%= pnews.image %>" class="<%= pnews.color %>">
            <div class="caption left-align">
                <h3><%= pnews.title %></h3>
                <h5 class="light grey-text text-lighten-3"><%= raw(pnews.body).truncate(200) %> <b><%= link_to t('layout.news.read_more'), news_path(pnews), :class => 'white-text'%></b> </h5>
            </div>
        </li>
        <% end %>
    </ul>
</div>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universidad XYZ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/partials/navbars' %>
  </div>
  
  <!-- Contenido de la pagina -->
  <div class="container">
      <%= yield %>
  </div>
  
  <!-- Footer -->
  <div class="container">
    <%= render 'layouts/partials/footer' %>
  </div>



  
  <!-- Scripts -->
  <script>
    // iniciar tootips
    $(document).ready(function(){
      $('.tooltipped').tooltip({delay: 50});
    });
    //iniciar dorpdown

    $(".dropdown-button").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: true, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
    // iniciar la barra lateral
    $(".button-collapse").sideNav();

    $(function() {

      //inicializador de los toast
      <% if notice %>
      Materialize.toast('<%= notice %>', 4000, 'green')
      <% end %>
      <% if alert %>
      Materialize.toast('<%= alert %>', 4000, 'red')
      <% end %>

      //para los elementos seleccionados en la navbar sean active en funcion de su href
      var url = window.location.toString();
      console.log(url);
      if (url.match('#')) {
        url = url.split('#')[0];
        console.log(url);
      }
      var element = $('.tabs .tab a').filter(function() {
        return this.href == url;
      }).addClass('active');

      console.log(element.parent());

      if(!element.parent().is('li.tab')){
        $('.indicator').removeClass('indicator');
        $('.tabs .tab a').removeClass('active');
      }
    });

  </script>

  <%= yield :scripts %>

</body>
</html>