config/routes.rb
Rails.application.routes.draw do
  get 'materials/index'

  get 'materials/new'

  get 'materials/create'

  get 'materials/destroy'

  scope "(:locale)", locale: /es|en/ do

    get 'member/:id/edit_membership' => 'members#edit_membership', as: :member_edit_membership

    resources :members do
      member do
        put :add_role
      end
    end

    resources :news
    resources :posts
    resources :subjects do
      resources :loads, only: [:index, :new, :create]
      resources :materials, only: [:index, :new, :create, :destroy]
    end
    resources :loads, only: [:update]

    resources :periods do
      resources :subjects, only: [:index, :new, :create]
    end

    resources :subjects, only: [:show, :edit, :update, :destroy]
    get '/subjects/:id/participants', to: 'subjects#participants', as: 'subject_users'

    get '/periods_list', to: 'periods#list', as: 'periods_list'
    get '/teachers', to: 'members#teachers', as: 'members_teachers'
    get '/apiusers', to: 'members#apiusers', as: 'api_users'
    get '/members/:user_id/qualifications', to: 'members#qualifications', as: 'member_qualifications'

    devise_for :users

  end

  root 'welcome#index'
  get '/:locale' => 'welcome#index'
  

    

end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 10
  has_many :news
  has_and_belongs_to_many :roles 
  accepts_nested_attributes_for :roles
  has_many :loads
  has_many :subjects, through: :loads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def role?( role ) 
        !roles.find_by_name( role ).nil?
    end 

    def role_id?( role ) 
        !roles.find_by_id( role ).nil?
    end 

    def active_for_authentication? 
        super && approved? 
    end

    def subjectLoad?(subject)
        !loads.find_by_subject_id(subject).nil?
    end

    def inactive_message 
        if !approved? 
          :not_approved 
        else 
            super # Use whatever other message 
        end 
    end
    
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :find_user,   only: [:edit_membership, :update]

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false).page params[:page]
      @all_user = false;
    else
      @users = User.page params[:page]
      @all_user = true;
    end

    authorize! :read, @users
    @countAll = User.count

  end

  def edit_membership
  end

  def apiusers
    @users = User.all.collect {|p| [ p.email, 'null' ] }.to_h
    respond_to do |format|
      format.json { render :json => @users, :status => 200 }
      format.html { render :json => @users, :status => 200 }
    end
  end

  def teachers
    @users = User.joins(:roles).where(:roles => {:name => 'profesor'}).collect {|p| [ p.email, 'null' ] }.to_h
    respond_to do |format|
      format.json { render :json => @users, :status => 200 }
      format.html { render :json => @users, :status => 200 }
    end
  end

  def update
    if @user.update_attributes(member_params)
      @user.roles <<  Role.find(params[:role_ids]) if params[:role_ids]
      @user.save
      redirect_to member_edit_membership_path(@user), :notice => "Membership updated"
    else
      render 'edit_membership'
    end
  end

  def qualifications
    authorize! :qualifications, User
  end

  # Confirms the correct user.
  def find_user
    @user = User.find(params[:id])
  end

  def member_params
    params.require(:user).permit(:approved, :role_ids => [])
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit_membership.html.erb
<% content_for :breadcrumb do %>
<%= link_to "Users", members_path, class: 'breadcrumb' %>
<%= link_to @user.email, member_edit_membership_path(@user.id), class: 'breadcrumb' %>
<% end %>


<div class="row no-margin-bottom">
    <div class="col s12 m6 red subsection">
        <div class="header-section-img white-text">
            <h4><%= t('layout.users.edit_membership') %></h4>
        </div>
    </div>
    <div class="col s6 m3 grey darken-4 subsection">
        <i class="fa fa-envelope large "></i>
        <h5 class="grey-text text-light-1"><b><%= t('layout.users.email') %></b></h5>
        <span class="white-text header-text"><%= @user.email %> </span>
    </div>
    <div class="col s6 m3 grey darken-3 subsection">
        <i class="fa fa-id-badge large "></i>
        <h5 class="grey-text text-light-1"><%= t('layout.users.current_roles') %></h5>
        <% @user.roles.each do |role| %>

        <span class="white-text header-text"><%= role.name %></span><br>

        <% end %>
        
    </div>
</div>
<div class="row no-margin-bottom">
    <div class="col s6 m2 grey darken-4 subsection section-medium">
        <h5 class="grey-text"><%= t('layout.users.created_at') %></h5>
        <div class="center white-text date-section">
            <span class="flow-text year"><%= @user.created_at.strftime('%Y') %></span><br>
            <span class="center day"><b><%= @user.created_at.strftime('%d') %></b></span><br>
            <div class="right month">
                <span class="grey darken-4 month-name"><b><%= @user.created_at.strftime('%B') %></b></span> 
            </div>
        </div>
    </div>
    <div class="col s6 m2 grey darken-3 subsection section-medium">
        <h5 class="grey-text"><%= t('layout.users.updated_at') %></h5>
        <div class="center white-text date-section">
            <span class="flow-text year"><%= @user.updated_at.strftime('%Y') %></span><br>
            <span class="center day"><b><%= @user.updated_at.strftime('%d') %></b></span><br>
            <div class="right month">
                <span class="grey darken-3 month-name"><b><%= @user.updated_at.strftime('%B') %></b></span> 
            </div>
        </div>
    </div>
    <div class="col s12 m8 white" style="padding:25px;">
        <h3><%= @user.email %></h3>
        <%= form_for(@user, url: member_path(@user), html: { method: :put }) do |f| %>
        <!-- Switch -->
        <div class="row" style="padding: 0 0.75rem;">
            <div class="col s12 m10">
                <%= f.label :approved%>
                <p>
                    <div class="switch">
                        <label>
                            <%= t('layout.users.no_approved') %>
                            <%= f.check_box :approved%>
                            <span class="lever"></span>
                            <%= t('layout.users.yes_approved') %>
                        </label>
                    </div> 
                </p>
            </div>
            
        </div>

        <div class="row" style="padding: 0 0.75rem;">
            <div class="input-field col s12 m10" >
                <%= f.select :role_ids, Role.all.collect {|p| [ p.name, p.id ] }.prepend(['Choose roles', '']), {:disabled => ''}, { multiple: true} %>
                <%= f.label :roles%>
            </div>
        </div>

        <p>
            <%= f.submit t('layout.users.update'), class: 'btn red' %>
        </p>

        <% end %>
    </div>
</div>

<div class="row no-margin-bottom">
    <div class="col s12">
        <div class="" style="margin-top:40px;">
            <h4 class="center-align "><%= t('layout.users.roles_information') %></h4>
        </div>
    </div>

    <div class="col s4" style="padding:20px;">
        <div class="center promo promo-example">
            <i class="fa fa-unlock"></i>
            <p class="promo-caption">Super_admin</p>
            <p class="light center"><%= t('layout.users.super_admin') %>.</p>
        </div>
    </div>
    <div class="col s4" style="padding:20px;">
        <div class="center promo promo-example">
            <i class="fa fa-unlock-alt"></i>
            <p class="promo-caption">Profesor</p>
            <p class="light center"><%= t('layout.users.profesor') %>.</p>
        </div>
    </div>
    <div class="col s4" style="padding:20px;">
        <div class="center promo promo-example">
            <i class="fa fa-lock"></i>
            <p class="promo-caption">Estudiante</p>
            <p class="light center"><%= t('layout.users.estudiante') %>.</p>
        </div>
    </div>
</div>


<% content_for :scripts do %>
<script>

</script>
<% end %>

app/views/members/index.html.erb
<% content_for :breadcrumb do %>
<%= link_to t('layout.users.title'), members_path, class: 'breadcrumb grey-text text-darken-3' %>
<% end %>

<div class="row no-margin-bottom">
    <div class="col s12 m6 grey darken-4 subsection with-image-users">
        <img src="" alt="">
        <div class="header-section-img white-text">
            <h4>Users</h4>
        </div>
    </div>
    <div class="col s12 m3 subsection grey <%= @all_user? 'darken-4 triangle' : 'darken-3' %> ">
        <i class="fa fa-users large "></i>
        <h5 class="white-text"><%= t('layout.users.all_users') %></h5>
        <span class="white-text header-number"><b><%= @countAll %></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.users.view_all'), { :controller => "members", :action => 'index' }, :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
        
    </div>
    <div class="col s12 m3 subsection grey <%= !@all_user? 'darken-4 triangle' : 'darken-3' %>">
        <i class="fa fa-user-plus large"></i>
        <h5 class="white-text"><%= t('layout.users.awaitting_approval') %></h5>
        <span class="white-text header-number"><b><%= @users.where(approved: false).total_count %></b>   </span>
        <div style="position:absolute;left:30px;bottom:30px;">
            <%= link_to t('layout.users.view'), { :controller => "members", :action => 'index', :approved => "false" }, :class=>"btn waves-effect waves-light grey light-2 white-text z-depth-0" %>
        </div>
    </div>
</div>
<div class="row no-margin-bottom">
    <div class="col s12 m2 grey darken-4" style="min-height:100px;">
        <p>
            <div class="input-field white-text white-input col s12">
                <input id="icon_prefix" type="text" class="validate">
                <label for="icon_prefix"><%= t('layout.search') %></label>
            </div>
        </p>
        
    </div>
    <div class="col s12 m10 white" style="padding:25px;">

        <table class="responsive-table centered striped">
            <thead>
                <tr>
                    <th><%= t('layout.users.email') %></th>
                    <th><%= t('layout.users.approved') %></th>
                    <th></th>
                </tr>
            </thead>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.email %></td> 
                <td><%= user.approved %></td> 
                <td><%= link_to t('layout.users.edit_membership'), member_edit_membership_path(user.id), :class => 'btn waves-effect red' %></td>
            </tr>
            <% end %>
        </table>
        <div class="right">
            <%= paginate @users, :params => {:controller => 'members', :action => 'index', :approved => @all_user} %> 
        </div>
        
    </div>
</div>

app/views/members/qualifications.html.erb
<% content_for :breadcrumb do %>
<%= link_to "Qualifications", member_qualifications_path(current_user.id), class: 'breadcrumb' %>
<% end %>
<div class="row no-margin-bottom">
  <div class="col s12 m9 white">
    <ul class="collapsible" data-collapsible="accordion">
      <% current_user.subjects.group_by(&:period).each do |period, subjects| %>
      <li>
        <div class="collapsible-header">
          <i class="material-icons">library_books</i><%= period.year %> - <%= period.semester %> 
          <span class="right"><b>Promedio: <%= Load.all.where(:subject_id => period.subjects.collect {|s| s.id}, :user_id => current_user.id).average(:qualification).round(2) %></b></span> 
        </div>
        <div class="collapsible-body">
          <p>
            <% subjects.each do |subject| %>
            <a href="<%= subject_path(subject) %>"><%= subject.name %></a> - 
            <%= subject.qualification(current_user.id) %> <br>
            <% end %>
          </p>
        </div> 
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col s12 m3 grey darken-4 subsection section-medium">
    <h5 class="grey-text"> Global </h5>
    <% if current_user.loads.count > 0 %>
    <h3 class="center white-text"><%= current_user.loads.average(:qualification).round(2) %></h3>
    <% end %>
  </div>
  
</div>


<% content_for :scripts do %>
<script>

  $(document).ready(function(){
    $('.collapsible').collapsible();
  });

</script>
<% end %>